const ctl = '/data/adb/modules/rafperos_extreme_optimizer/common/rafperctl';
const groups = [
  { id: 'cpu', title: 'CPU / scheduler / frequência', keys: ['CPU_GOV','CPU_SCHEDUTIL','CPU_UCLAMP','CPU_CPUSET','CPU_STUNE','CPU_SOFT_FREQ_LOCK','CPU_ANTI_OSC','CPU_TOUCH_BOOST'] },
  { id: 'memory', title: 'Memória', keys: ['MEMORY_VM','MEMORY_ZRAM','MEMORY_DIRTY','MEMORY_LMKD','MEMORY_EXTREME'] },
  { id: 'render', title: 'Renderização / animações / compositor', keys: ['RENDER_HWUI','RENDER_SF','RENDER_ADVANCED','RENDER_ANIMATIONS'] },
  { id: 'gpu', title: 'GPU', keys: ['GPU_GOV','GPU_BOOST'] },
  { id: 'io', title: 'I/O e storage', keys: ['IO_SCHED','IO_LATENCY'] },
  { id: 'input', title: 'Input / toque / fingerprint', keys: ['INPUT_TOUCH','INPUT_FINGERPRINT'] },
  { id: 'advanced', title: 'Avançado', keys: ['ADV_BACKGROUND','ADV_THERMAL','APPLY_ON_BOOT'] },
  { id: 'experience', title: 'Experience Enhancers', keys: ['EXP_STEREO','EXP_SMOOTHNESS','EXP_TOUCH_RESPONSE','EXP_ANIMATION_BURST','EXP_GAME_SESSION','EXP_FOREGROUND_PRIORITY','EXP_AUDIO_BASS','EXP_AUDIO_VOICE','EXP_AUDIO_NORMALIZE','EXP_AUDIO_LIMITER','EXP_AUDIO_GAMING','EXP_VISUAL_CONSISTENCY','EXP_SESSION_BOOST','EXP_APP_LAUNCH','EXP_HAPTIC','EXP_BRIGHTNESS_RESPONSE','EXP_NETWORK_LATENCY'] },
];
const descriptions = {
  CPU_GOV:'Seleciona governor suportado para reduzir ramp-up lento.', CPU_SCHEDUTIL:'Ajusta rate limits de schedutil/interactive para bursts curtos.', CPU_UCLAMP:'Eleva utilização mínima de foreground/top-app.', CPU_CPUSET:'Afina afinidade foreground/top-app/background.', CPU_STUNE:'Boost legacy schedtune quando disponível.', CPU_SOFT_FREQ_LOCK:'Mantém piso temporário de frequência com timeout; não trava no máximo.', CPU_ANTI_OSC:'Aumenta down-rate-limit para reduzir sobe/desce de clocks.', CPU_TOUCH_BOOST:'Boost curto em interação.',
  MEMORY_VM:'Swappiness, watermarks e cache pressure.', MEMORY_ZRAM:'Read-ahead da fila zRAM.', MEMORY_DIRTY:'Dirty ratios, expiry e writeback.', MEMORY_LMKD:'LMK clássico e cache do ActivityManager.', MEMORY_EXTREME:'Gate manual para memória extrema; use com cautela.',
  RENDER_HWUI:'Hints reais de HWUI/RenderEngine.', RENDER_SF:'Hints de frame pacing SurfaceFlinger.', RENDER_ADVANCED:'Overrides debug de composição; risco de instabilidade visual.', RENDER_ANIMATIONS:'Escalas de animação Android por perfil.',
  GPU_GOV:'Governor devfreq/KGSL/Mali quando exposto.', GPU_BOOST:'Pwrlevel/clock boost GPU por endpoints reais.', IO_SCHED:'Scheduler de bloco suportado.', IO_LATENCY:'Read-ahead, iostats e low_latency quando disponíveis.', INPUT_TOUCH:'Touch boost curto.', INPUT_FINGERPRINT:'Boost de unlock/fingerprint sem burlar autenticação.', ADV_BACKGROUND:'Retenção de processos em cache.', ADV_THERMAL:'Modo performance vendor reversível; não desativa proteções.', APPLY_ON_BOOT:'Consentimento para reaplicar toggles ativos no boot.',
  EXP_STEREO:'Stereo Enhancer por tinymix quando o codec expõe controle real; níveis por perfil.', EXP_AUDIO_BASS:'Bass boost controlado via mixer real quando disponível.', EXP_AUDIO_VOICE:'Clareza de voz/diálogo via controle de codec/DSP exposto.', EXP_AUDIO_NORMALIZE:'Normalização/DRC de volume se houver controle real.', EXP_AUDIO_LIMITER:'Limiter para reduzir clipping quando exposto pelo áudio.', EXP_AUDIO_GAMING:'Caminho de áudio game/low-latency se o stack expõe controle.', EXP_SMOOTHNESS:'Hints de smoothness/frame pacing para reduzir sensação de travamento.', EXP_TOUCH_RESPONSE:'Touch response smoothing com boost curto em endpoints reais.', EXP_ANIMATION_BURST:'Burst para launcher, recents, shade e transições intensas.', EXP_GAME_SESSION:'Game Session Mode manual com boost de CPU/GPU/scheduler detectado.', EXP_FOREGROUND_PRIORITY:'Favorece UI/foreground via cpuset/uclamp/stune.', EXP_VISUAL_CONSISTENCY:'Prioriza consistência de frames sobre pico bruto via render hints.', EXP_SESSION_BOOST:'Boost forte durante sessão ativa com relaxamento por timeout.', EXP_APP_LAUNCH:'Abertura de apps mais rápida via burst de input/scheduler.', EXP_HAPTIC:'Haptic boost controlado se vibrator sysfs existir.', EXP_BRIGHTNESS_RESPONSE:'Tuning seguro de resposta visual/backlight apenas em endpoints próprios.', EXP_NETWORK_LATENCY:'Preferência de latência TCP para uso interativo sem quebrar conectividade.'
};
const risky = new Set(['MEMORY_EXTREME','RENDER_ADVANCED','ADV_THERMAL','APPLY_ON_BOOT','CPU_SOFT_FREQ_LOCK','GPU_BOOST','EXP_STEREO','EXP_AUDIO_BASS','EXP_AUDIO_GAMING','EXP_GAME_SESSION','EXP_SESSION_BOOST','EXP_BRIGHTNESS_RESPONSE']);
async function exec(cmd){ if(window.ksu?.exec){const r=await ksu.exec(cmd);return r.stdout||r.stderr||'';} if(window.KSU?.exec)return await KSU.exec(cmd); return 'KSU exec API não disponível.'; }
function parse(text){ const values={}, support={}; text.split('\n').forEach(line=>{ if(line.includes('=')&&!line.startsWith('---')&&!line.startsWith('#')){const [k,...v]=line.split('=');values[k]=v.join('=');} if(line.includes(':')){const [k,s,...rest]=line.split(':');support[k]={state:s,note:rest.join(':')};} }); return {values,support}; }
function badgeState(s){ return ['supported','partial','manual','advanced','unsupported'].includes(s)?s:'unknown'; }
function build(values,support){ const root=document.getElementById('featureSections'); root.innerHTML=''; groups.forEach(g=>{ const sec=document.createElement('section'); sec.innerHTML=`<div class="section-head"><h2>${g.title}</h2><button class="secondary" data-reset="${g.id}">Restaurar seção</button></div><div class="cards"></div>`; const cards=sec.querySelector('.cards'); g.keys.forEach(k=>{ const sup=support[k]||{state:'unknown',note:'Sem detecção ainda'}; const checked=values[k]==='1'; const card=document.createElement('div'); card.className='feature-card'+(risky.has(k)?' risky':''); card.innerHTML=`<div class="feature-head"><label><input type="checkbox" ${checked?'checked':''}>${k}</label><span class="badge ${badgeState(sup.state)}">${sup.state}</span></div><p>${sup.note}</p><p class="impact">${descriptions[k]||''}</p>${risky.has(k)?'<p class="risk">⚠️ Opção agressiva/manual. Ative apenas se entender o risco.</p>':''}`; card.querySelector('input').onchange=async e=>{ if(e.target.checked&&risky.has(k)&&!confirm(`${k} é agressivo. Ativar mesmo assim?`)){ e.target.checked=false; return; } await exec(`${ctl} toggle ${k} ${e.target.checked?1:0}`); refresh(); }; cards.appendChild(card); }); sec.querySelector('[data-reset]').onclick=async()=>{ await exec(`${ctl} reset-section ${g.id}`); refresh(); }; root.appendChild(sec); }); }
async function refresh(){ const st=await exec(`${ctl} status`); document.getElementById('status').textContent=st; const {values,support}=parse(st); document.querySelectorAll('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===values.profile)); build(values,support); document.getElementById('logs').textContent=await exec(`${ctl} logs 260`); }
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=async()=>{await exec(`${ctl} profile ${b.dataset.profile}`);refresh();});
document.getElementById('apply').onclick=async()=>{await exec(`${ctl} apply webui`);refresh();};
document.getElementById('boost').onclick=async()=>{await exec(`${ctl} boost`);refresh();};
document.getElementById('reset').onclick=async()=>{if(confirm('Reset total e restauração dos valores originais?')){await exec(`${ctl} reset webui`);refresh();}};
refresh(); setInterval(refresh,5000);
